### ISSUE TITLE
Under H1 HTML displays Posted on (timestamp...

### ISSUE THREAD

**Issue by elliottw** [Zilong-Li/org-tufte#1]
Thanks for a super easy way to implement tufte css. Hopefully a quick question:

Under H1 and above the TOC, I'm getting:
```
Posted on (timestamp (:type inactive :raw-value [2024-03-03 Sun 21:03] :year-start 2024 :month-start 3 :day-start 3 :hour-start 21 :minute-start 3 :year-end 2024 :month-end 3 :day-end 3 :hour-end 21 :minute-end 3 :begin 1 :end 23 :post-blank 0 :parent (#0)))
```

Is this a feature? Is there something wrong with the formatting of my org-mode file? I'm currently using denote which adds some front matter, but it doesn't seem to be causing this.

**Comment by Zilong-Li** [comment]
Thanks for giving feedback! 

Yes, this  is a new feature of v0.3.0 now ! Please try it again with the latest version!

**Comment by elliottw** [comment]
Nice! I guess I pulled down a version before this was all buttoned up. Great job. Think you'll ever pull in the fonts from tufte-css?
