### ISSUE TITLE
A way to run it locally 

### ISSUE THREAD

**Issue by filipecfv** [Zilong-Li/org-tufte#3]
Hi! Very good and handy package.

But I'm having a hard time to replace this line `"<link rel=\"stylesheet\" href=\"https://zilongli.org/code/tufte.css\" type=\"text/css\" />\n" ` with a local file on my computer. I'm basically copying all the content in https://zilongli.org/code/tufte.css\, saving it locally as `tufte.css` in the same folder where org-tufte.el is located and then replacing that line of code with `"<link rel=\"stylesheet\" href=\"tufte.css\" type=\"text/css\" />\n"`. 

It doesn't work properly; all sidenotes are rendered weirdly, as check-boxes and not rightly aligned to the side, but rather embedded in the text.

I just want a way to run it locally and not depend upon your files. I'm not really familiar with HTML, rather an amateur; so I would be glad if you could help me.

**Comment by Zilong-Li** [comment]
Hi, I am on vacation now 

A quick fix is to substitute the css of my site to your local copies,which has to be either the absolute local path or the relative path to your html file.

Let me if the absolute path works.

**Comment by filipecfv** [comment]
Yes, it did work. I downloaded all tufte files and now it works. Thank you.
